/**
 * 计算文档 — 可插入函数/语法目录（与 CalculatorEngine + math.js + 金融模块一致）
 * 供工具栏「插入函数」下拉与 AI system 提示摘要共用
 */

export type CalculatorCaretHint = 'end' | 'firstParenInside';

export interface CalculatorFunctionEntry {
  id: string;
  nameEn: string;
  nameZh: string;
  syntax: string;
  descriptionZh: string;
  descriptionEn: string;
  /** 插入到当前光标的片段 */
  insertTemplate: string;
  /** 插入后光标位置策略 */
  caretHint: CalculatorCaretHint;
  tags: string[];
}

export interface CalculatorFunctionCategory {
  id: string;
  labelKey: string;
  order: number;
  functions: CalculatorFunctionEntry[];
}

export const CALCULATOR_FUNCTION_CATEGORIES: CalculatorFunctionCategory[] = [
  {
    id: 'financial',
    labelKey: 'calculator.fnCategory.financial',
    order: 0,
    functions: [
      {
        id: 'pmt',
        nameEn: 'pmt',
        nameZh: '等额还款',
        syntax: 'pmt(rate, nper, pv, fv?, type?)',
        descriptionZh: '每期还款额；rate 为每期利率，nper 为总期数，pv 为现值（贷款本金，通常取负）',
        descriptionEn: 'Payment per period; rate per period, nper periods, pv present value (loan principal, often negative).',
        insertTemplate: 'pmt(, , )',
        caretHint: 'firstParenInside',
        tags: ['pmt', '月供', '还款', '贷款', 'payment'],
      },
      {
        id: 'npv',
        nameEn: 'npv',
        nameZh: '净现值',
        syntax: 'npv(cashFlows, rate) 或整行金融解析',
        descriptionZh: '现金流数组与折现率；也可写自然语言行由引擎解析',
        descriptionEn: 'NPV from cash flow array and discount rate.',
        insertTemplate: 'npv([], 0.1)',
        caretHint: 'firstParenInside',
        tags: ['npv', '净现值', '现金流'],
      },
      {
        id: 'irr',
        nameEn: 'irr',
        nameZh: '内部收益率',
        syntax: 'irr(cashFlows)',
        descriptionZh: '现金流数组的内部收益率',
        descriptionEn: 'Internal rate of return for cash flows.',
        insertTemplate: 'irr([])',
        caretHint: 'firstParenInside',
        tags: ['irr', '收益率'],
      },
      {
        id: 'fv',
        nameEn: 'fv',
        nameZh: '终值',
        syntax: 'fv(rate, nper, pmt, pv?, type?)',
        descriptionZh: '年金终值',
        descriptionEn: 'Future value of an annuity.',
        insertTemplate: 'fv(, , )',
        caretHint: 'firstParenInside',
        tags: ['fv', '终值', 'future'],
      },
      {
        id: 'pv',
        nameEn: 'pv',
        nameZh: '现值',
        syntax: 'pv(rate, nper, pmt, fv?, type?)',
        descriptionZh: '年金现值',
        descriptionEn: 'Present value of an annuity.',
        insertTemplate: 'pv(, , )',
        caretHint: 'firstParenInside',
        tags: ['pv', '现值', 'present'],
      },
      {
        id: 'nper',
        nameEn: 'nper',
        nameZh: '期数',
        syntax: 'nper(rate, pmt, pv, fv?, type?)',
        descriptionZh: '在固定利率与每期还款额下，还清 pv（与 fv）所需的期数；type 0=期末 1=期初。',
        descriptionEn: 'Number of periods to pay off at given rate and payment; type 0=end, 1=begin of period.',
        insertTemplate: 'nper(, , )',
        caretHint: 'firstParenInside',
        tags: ['nper', '期数', '还款期'],
      },
      {
        id: 'rate',
        nameEn: 'rate',
        nameZh: '每期利率',
        syntax: 'rate(nper, pmt, pv, fv?, type?, guess?, tol?, maxIter?)',
        descriptionZh: '由期数、现金流反解每期利率（迭代，可能 NaN）；通常与 pmt 互为反算。勿用 rate 作变量名（已保留为函数）。',
        descriptionEn: 'Solve per-period rate from nper, payment, pv, fv (iterative; may be NaN). Do not use "rate" as a variable name.',
        insertTemplate: 'rate(, , )',
        caretHint: 'firstParenInside',
        tags: ['rate', '利率', '反解'],
      },
      {
        id: 'ipmt',
        nameEn: 'ipmt',
        nameZh: '当期利息',
        syntax: 'ipmt(rate, per, nper, pv, fv?, type?)',
        descriptionZh: '第 per 期还款中的利息部分（per 从 1 起）；与 ppmt 之和为当期总还款（与 pmt 一致模型下）。',
        descriptionEn: 'Interest portion of payment for period per (1-based); ipmt+ppmt ≈ pmt under same conventions.',
        insertTemplate: 'ipmt(, 1, , )',
        caretHint: 'firstParenInside',
        tags: ['ipmt', '利息', '摊还'],
      },
      {
        id: 'ppmt',
        nameEn: 'ppmt',
        nameZh: '当期本金',
        syntax: 'ppmt(rate, per, nper, pv, fv?, type?)',
        descriptionZh: '第 per 期还款中的本金部分；常与 ipmt 对照做摊还表。',
        descriptionEn: 'Principal portion of payment for period per (1-based).',
        insertTemplate: 'ppmt(, 1, , )',
        caretHint: 'firstParenInside',
        tags: ['ppmt', '本金', '摊还'],
      },
      {
        id: 'mirr',
        nameEn: 'mirr',
        nameZh: '修正内部收益率',
        syntax: 'mirr(cashFlows, financeRate, reinvestRate)',
        descriptionZh: '现金流分别按融资成本与再投资率折现后的修正 IRR；需至少一正一负现金流。',
        descriptionEn: 'MIRR with separate finance and reinvestment rates; needs positive and negative flows.',
        insertTemplate: 'mirr([], 0.05, 0.08)',
        caretHint: 'firstParenInside',
        tags: ['mirr', '修正收益率'],
      },
      {
        id: 'xnpv',
        nameEn: 'xnpv',
        nameZh: '不规则日期净现值',
        syntax: 'xnpv(rate, values, dates)',
        descriptionZh: '年折现率 rate；values 与 dates 等长；dates 为 Excel 序列日或相对天数（同单位），绝对值大于 1e9 视为 Unix 毫秒；首日为基准，按 365 天年折现（对齐 Excel XNPV）。',
        descriptionEn: 'NPV with irregular dates; dates align with cash flows; Excel XNPV convention (365-day year).',
        insertTemplate: 'xnpv(0.1, [], [])',
        caretHint: 'firstParenInside',
        tags: ['xnpv', 'XNPV', '日期', '现金流'],
      },
      {
        id: 'xirr',
        nameEn: 'xirr',
        nameZh: '不规则日期内部收益率',
        syntax: 'xirr(values, dates, guess?)',
        descriptionZh: '使 xnpv=0 的年化收益率；需至少一正一负现金流；guess 可选（默认 0.1）。',
        descriptionEn: 'Annual IRR for irregular dates; XIRR-style; requires sign change.',
        insertTemplate: 'xirr([], [], 0.1)',
        caretHint: 'firstParenInside',
        tags: ['xirr', 'XIRR', 'IRR'],
      },
      {
        id: 'ear',
        nameEn: 'EAR',
        nameZh: '有效年利率',
        syntax: '(1 + 名义年利率 / m) ^ m - 1',
        descriptionZh: 'm 为每年复利次数；与不同复利频率的名义利率对比时用。',
        descriptionEn: 'Effective annual rate from nominal rate compounded m times per year.',
        insertTemplate: '(1 + 名义年利率 / 12) ^ 12 - 1',
        caretHint: 'end',
        tags: ['EAR', '有效年利率', '复利'],
      },
      {
        id: 'nominal_from_eff',
        nameEn: 'nominal from EAR',
        nameZh: '名义年利率（由有效反推）',
        syntax: 'm * ((1 + EAR) ^ (1/m) - 1)',
        descriptionZh: '已知有效年利率与年复利次数 m，反推名义年利率。',
        descriptionEn: 'Nominal annual rate from EAR and compounding frequency m.',
        insertTemplate: '12 * ((1 + EAR) ^ (1/12) - 1)',
        caretHint: 'end',
        tags: ['名义利率', 'EAR'],
      },
      {
        id: 'perpetuity_pv',
        nameEn: 'perpetuity PV',
        nameZh: '永续年金现值',
        syntax: '现金流 / 折现率',
        descriptionZh: '首期末起永续等额现金流；折现率为小数（如 0.08 表示 8%）。',
        descriptionEn: 'PV = C / r for perpetual payment C starting next period.',
        insertTemplate: '现金流 / 折现率',
        caretHint: 'end',
        tags: ['永续', '现值', '年金'],
      },
      {
        id: 'growing_perp_pv',
        nameEn: 'Gordon PV',
        nameZh: '增长永续现值',
        syntax: '下期现金流 / (折现率 - 增长率)',
        descriptionZh: '增长率 < 折现率；用于股利贴现简化模型等。',
        descriptionEn: 'PV = C1 / (r - g), require r > g.',
        insertTemplate: '下期现金流 / (折现率 - 增长率)',
        caretHint: 'end',
        tags: ['戈登', '增长', 'DDM'],
      },
      {
        id: 'loan_balance',
        nameEn: 'loan balance',
        nameZh: '剩余本金',
        syntax: 'pv * (1+rate)^n + pmt * ((1+rate)^n - 1) / rate',
        descriptionZh: '标准摊还模型；rate 为每期利率，n 为已还期数，pmt 与 pmt() 输出同号约定。',
        descriptionEn: 'Outstanding balance after n payments (standard amortization).',
        insertTemplate: 'pv * (1+rate)^n + pmt * ((1+rate)^n - 1) / rate',
        caretHint: 'end',
        tags: ['剩余本金', '贷款余额', '摊还'],
      },
      {
        id: 'discount_factor',
        nameEn: 'discount factor',
        nameZh: '折现因子',
        syntax: '1 / (1 + r) ^ t',
        descriptionZh: 't 期后 1 元现值；r 为每期折现率。',
        descriptionEn: 'Present value of 1 received in t periods.',
        insertTemplate: '1 / (1 + r) ^ t',
        caretHint: 'end',
        tags: ['折现', '因子', 'DCF'],
      },
      {
        id: 'rule_of_72',
        nameEn: 'Rule of 72',
        nameZh: '72 法则',
        syntax: '72 / (年化收益率 * 100)',
        descriptionZh: '近似翻倍年数；收益率用小数（8% → 0.08）时写 72 / (0.08*100) 或改用 72/8 若用百分数。',
        descriptionEn: 'Approximate years to double at rate r.',
        insertTemplate: '72 / 8',
        caretHint: 'end',
        tags: ['72', '翻倍', '复利'],
      },
      {
        id: 'fv_lump_sum',
        nameEn: 'FV lump sum',
        nameZh: '单笔复利终值',
        syntax: 'pv * (1 + r) ^ n',
        descriptionZh: 'pv 现值，r 每期利率，n 期数。',
        descriptionEn: 'Future value of a single sum under compound interest.',
        insertTemplate: 'pv * (1 + r) ^ n',
        caretHint: 'end',
        tags: ['终值', '复利', '单笔'],
      },
      {
        id: 'compound',
        nameEn: 'compound',
        nameZh: '复利终值',
        syntax: 'compound(principal, rate, periods)',
        descriptionZh: '复利终值；principal 本金，rate 每期利率（小数），periods 期数。',
        descriptionEn: 'Compound interest future value; principal, rate per period (decimal), periods.',
        insertTemplate: 'compound(, , )',
        caretHint: 'firstParenInside',
        tags: ['终值', '复利'],
      },
      {
        id: 'discount',
        nameEn: 'discount',
        nameZh: '折现值',
        syntax: 'discount(futureValue, rate, periods)',
        descriptionZh: '折现值；futureValue 终值，rate 每期利率（小数），periods 期数。',
        descriptionEn: 'Present value (discount); future value, rate per period (decimal), periods.',
        insertTemplate: 'discount(, , )',
        caretHint: 'firstParenInside',
        tags: ['折现', '现值'],
      },
      {
        id: 'roi',
        nameEn: 'ROI',
        nameZh: '投资回报率',
        syntax: 'roi(gain, cost)',
        descriptionZh: '投资回报率 ROI；gain 收益（售价 - 成本），cost 成本。',
        descriptionEn: 'Return on Investment; gain (selling price - cost), cost.',
        insertTemplate: 'roi(, )',
        caretHint: 'firstParenInside',
        tags: ['回报率', 'ROI'],
      },
      {
        id: 'annualized_return',
        nameEn: 'annualizedReturn',
        nameZh: '年化收益率',
        syntax: 'annualizedReturn(totalReturn, days)',
        descriptionZh: '年化收益率；totalReturn 总回报率（如 0.5 表示 50%），days 持有天数。',
        descriptionEn: 'Annualized return; totalReturn (e.g. 0.5 for 50%), days held.',
        insertTemplate: 'annualizedReturn(, )',
        caretHint: 'firstParenInside',
        tags: ['年化', '收益率'],
      },
      {
        id: 'pmt_annuity_due',
        nameEn: 'annuity due note',
        nameZh: '期初年金与期末',
        syntax: 'pmt(..., type: 1)',
        descriptionZh: '金融函数 type：0=期末（默认），1=期初；期初年金可先算期末再 /(1+rate) 调整。',
        descriptionEn: 'type 1 = beginning of period in pmt/fv/pv when supported.',
        insertTemplate: 'pmt(rate, nper, pv, 0, 1)',
        caretHint: 'firstParenInside',
        tags: ['期初', '年金', 'type'],
      },
    ],
  },
  {
    id: 'equities',
    labelKey: 'calculator.fnCategory.equities',
    order: 1,
    functions: [
      {
        id: 'eq_pe',
        nameEn: 'PE',
        nameZh: '市盈率',
        syntax: '股价 / EPS 或 总市值 / 净利润',
        descriptionZh: '每股市价相对每股收益；注意 TTM/静态口径一致。',
        descriptionEn: 'Price / EPS or market cap / net income; keep TTM vs trailing consistent.',
        insertTemplate: '股价 / EPS',
        caretHint: 'end',
        tags: ['PE', '市盈率', '估值'],
      },
      {
        id: 'eq_pb',
        nameEn: 'PB',
        nameZh: '市净率',
        syntax: '股价 / 每股净资产',
        descriptionZh: '市值相对净资产；金融股常用。',
        descriptionEn: 'Price / book value per share.',
        insertTemplate: '股价 / 每股净资产',
        caretHint: 'end',
        tags: ['PB', '市净率'],
      },
      {
        id: 'eq_ps',
        nameEn: 'PS',
        nameZh: '市销率',
        syntax: '总市值 / 营业收入',
        descriptionZh: '市值相对营收；亏损或未盈利公司参考。',
        descriptionEn: 'Market cap / revenue.',
        insertTemplate: '总市值 / 营业收入',
        caretHint: 'end',
        tags: ['PS', '市销率'],
      },
      {
        id: 'eq_div_yield',
        nameEn: 'dividend yield',
        nameZh: '股息率',
        syntax: '每股股息 / 股价',
        descriptionZh: '近12个月股息/市价；与分红政策相关。',
        descriptionEn: 'Dividend per share / price.',
        insertTemplate: '每股股息 / 股价',
        caretHint: 'end',
        tags: ['股息率', '分红'],
      },
      {
        id: 'eq_eps',
        nameEn: 'EPS',
        nameZh: '每股收益',
        syntax: '净利润 / 总股本',
        descriptionZh: '归属母公司净利润除以加权股本。',
        descriptionEn: 'Net income / shares outstanding.',
        insertTemplate: '净利润 / 总股本',
        caretHint: 'end',
        tags: ['EPS', '每股盈利'],
      },
      {
        id: 'eq_bvps',
        nameEn: 'BVPS',
        nameZh: '每股净资产',
        syntax: '净资产 / 总股本',
        descriptionEn: 'Equity / shares outstanding.',
        descriptionZh: '归属母公司净资产除以股本。',
        insertTemplate: '净资产 / 总股本',
        caretHint: 'end',
        tags: ['BVPS', '每股净资产'],
      },
      {
        id: 'eq_roe',
        nameEn: 'ROE',
        nameZh: '净资产收益率',
        syntax: '净利润 / 净资产',
        descriptionZh: '杜邦可拆为净利率×资产周转率×权益乘数。',
        descriptionEn: 'Return on equity.',
        insertTemplate: '净利润 / 净资产',
        caretHint: 'end',
        tags: ['ROE', '净资产收益率'],
      },
      {
        id: 'eq_roa',
        nameEn: 'ROA',
        nameZh: '总资产收益率',
        syntax: '净利润 / 总资产',
        descriptionEn: 'Return on assets.',
        descriptionZh: '利润相对全部资产。',
        insertTemplate: '净利润 / 总资产',
        caretHint: 'end',
        tags: ['ROA'],
      },
      {
        id: 'eq_dupont',
        nameEn: 'DuPont ROE',
        nameZh: '杜邦 ROE',
        syntax: '净利率 * 资产周转率 * 权益乘数',
        descriptionZh: '净利率=净利润/营收；周转=营收/总资产；乘数=总资产/净资产。',
        descriptionEn: 'Margin × turnover × leverage.',
        insertTemplate: '净利率 * 资产周转率 * 权益乘数',
        caretHint: 'end',
        tags: ['杜邦', 'ROE'],
      },
      {
        id: 'eq_peg',
        nameEn: 'PEG',
        nameZh: 'PEG',
        syntax: 'PE / 盈利增速',
        descriptionZh: '增速用与 PE 匹配的口径（如百分数 20% 或小数 0.2 须统一）。',
        descriptionEn: 'PE / earnings growth; align % vs decimal.',
        insertTemplate: 'PE / 盈利增速',
        caretHint: 'end',
        tags: ['PEG', '成长'],
      },
      {
        id: 'eq_cagr',
        nameEn: 'CAGR',
        nameZh: '复合年化收益率',
        syntax: '(终值 / 初值) ^ (1 / 年数) - 1',
        descriptionZh: '多期几何平均；初终值须同口径。',
        descriptionEn: 'Geometric mean return over n years.',
        insertTemplate: '(终值 / 初值) ^ (1 / 年数) - 1',
        caretHint: 'end',
        tags: ['CAGR', '年化'],
      },
      {
        id: 'eq_hpr',
        nameEn: 'HPR',
        nameZh: '持有期收益率',
        syntax: '(卖出价 - 买入价) / 买入价',
        descriptionEn: 'Holding-period return ex-dividend unless adjusted.',
        descriptionZh: '未含股息再投时可另加股息项。',
        insertTemplate: '(卖出价 - 买入价) / 买入价',
        caretHint: 'end',
        tags: ['收益率', '价差'],
      },
      {
        id: 'eq_fcf_yield',
        nameEn: 'FCF yield',
        nameZh: '自由现金流收益率',
        syntax: '自由现金流 / 总市值',
        descriptionZh: 'FCF 与市值口径一致（TTM 等）。',
        descriptionEn: 'Free cash flow / market cap.',
        insertTemplate: '自由现金流 / 总市值',
        caretHint: 'end',
        tags: ['FCF', '现金流'],
      },
      {
        id: 'eq_interest_cover',
        nameEn: 'interest cover',
        nameZh: '利息覆盖倍数',
        syntax: '息税前利润 / 利息费用',
        descriptionEn: 'EBIT / interest expense.',
        descriptionZh: '偿债能力常用指标。',
        insertTemplate: '息税前利润 / 利息费用',
        caretHint: 'end',
        tags: ['利息覆盖', '偿债'],
      },
      {
        id: 'eq_net_margin',
        nameEn: 'net margin',
        nameZh: '净利率',
        syntax: '净利润 / 营业收入',
        descriptionEn: 'Net margin.',
        descriptionZh: '销售净利率。',
        insertTemplate: '净利润 / 营业收入',
        caretHint: 'end',
        tags: ['净利率'],
      },
      {
        id: 'eq_gross_margin',
        nameEn: 'gross margin',
        nameZh: '毛利率',
        syntax: '(营业收入 - 营业成本) / 营业收入',
        descriptionEn: 'Gross margin.',
        descriptionZh: '毛利占营收比。',
        insertTemplate: '(营业收入 - 营业成本) / 营业收入',
        caretHint: 'end',
        tags: ['毛利率'],
      },
      {
        id: 'eq_position_size',
        nameEn: 'position size',
        nameZh: '按风险定额的手数',
        syntax: '风险预算 / (止损幅度 * 每股价格)',
        descriptionZh: '风险预算=账户×单笔风险%；止损幅度为小数；示意非保证成交。',
        descriptionEn: 'Risk budget / (stop-loss % × price); illustrative.',
        insertTemplate: '风险预算 / (止损幅度 * 每股价格)',
        caretHint: 'end',
        tags: ['仓位', '止损'],
      },
      {
        id: 'eq_kelly',
        nameEn: 'Kelly',
        nameZh: '凯利公式（简化）',
        syntax: '(胜率 * 盈亏比 - (1-胜率)) / 盈亏比',
        descriptionZh: 'b=平均盈利/平均亏损；全凯利波动大，实务常乘分数系数。',
        descriptionEn: 'Simplified Kelly; use fractional Kelly in practice.',
        insertTemplate: '(胜率 * 盈亏比 - (1 - 胜率)) / 盈亏比',
        caretHint: 'end',
        tags: ['凯利', '仓位'],
      },
      {
        id: 'eq_sharpe',
        nameEn: 'Sharpe (simple)',
        nameZh: '夏普比率（简）',
        syntax: '(组合收益率 - 无风险利率) / 收益率标准差',
        descriptionZh: '期度一致；超额收益/波动，非年化时注明。',
        descriptionEn: 'Mean excess return / std dev; match frequency.',
        insertTemplate: '(组合收益率 - 无风险利率) / 收益率标准差',
        caretHint: 'end',
        tags: ['夏普', '风险调整'],
      },
      {
        id: 'eq_ev_ebitda',
        nameEn: 'EV/EBITDA',
        nameZh: '企业价值倍数',
        syntax: '企业价值 / EBITDA',
        descriptionEn: 'EV / EBITDA multiple.',
        descriptionZh: '杠杆差异较 PE 更可比的估值倍数。',
        insertTemplate: '企业价值 / EBITDA',
        caretHint: 'end',
        tags: ['EV', 'EBITDA'],
      },
      {
        id: 'eq_ev_sales',
        nameEn: 'EV/Sales',
        nameZh: '市销率（企业价值）',
        syntax: '企业价值 / 营业收入',
        descriptionZh: '与 PS（市值/营收）不同，分子为含债企业价值。',
        descriptionEn: 'EV divided by revenue; differs from market-cap-based P/S.',
        insertTemplate: '企业价值 / 营业收入',
        caretHint: 'end',
        tags: ['EV/S', '市销'],
      },
      {
        id: 'eq_p_fcf',
        nameEn: 'P/FCF',
        nameZh: '市值/自由现金流',
        syntax: '总市值 / 自由现金流',
        descriptionZh: '估值倍数；FCF 定义（经营现金流−资本开支）须与市值口径一致。',
        descriptionEn: 'Market cap / free cash flow; align FCF definition.',
        insertTemplate: '总市值 / 自由现金流',
        caretHint: 'end',
        tags: ['P/FCF', '自由现金流'],
      },
      {
        id: 'eq_roic',
        nameEn: 'ROIC',
        nameZh: '投入资本回报率',
        syntax: '税后营业利润 / 投入资本',
        descriptionZh: 'NOPAT/IC；投入资本可用权益+有息负债等口径，需前后一致。',
        descriptionEn: 'NOPAT / invested capital; keep definitions consistent.',
        insertTemplate: '税后营业利润 / 投入资本',
        caretHint: 'end',
        tags: ['ROIC', '投入资本'],
      },
      {
        id: 'eq_asset_turnover',
        nameEn: 'asset turnover',
        nameZh: '总资产周转率',
        syntax: '营业收入 / 总资产',
        descriptionZh: '营收对资产的运营效率。',
        descriptionEn: 'Revenue / total assets.',
        insertTemplate: '营业收入 / 总资产',
        caretHint: 'end',
        tags: ['周转率', '资产'],
      },
      {
        id: 'eq_inv_turnover',
        nameEn: 'inventory turnover',
        nameZh: '存货周转率',
        syntax: '营业成本 / 平均存货',
        descriptionZh: '可用销售天数 ≈ 365 / 周转率（按日历时调整）。',
        descriptionEn: 'COGS / average inventory.',
        insertTemplate: '营业成本 / 平均存货',
        caretHint: 'end',
        tags: ['存货', '周转'],
      },
      {
        id: 'eq_ar_days',
        nameEn: 'DSO',
        nameZh: '应收账款周转天数',
        syntax: '365 * 平均应收账款 / 营业收入',
        descriptionZh: '近似销售回款周期；也可用周转率倒数×365。',
        descriptionEn: 'Days sales outstanding approximation.',
        insertTemplate: '365 * 平均应收账款 / 营业收入',
        caretHint: 'end',
        tags: ['DSO', '应收'],
      },
      {
        id: 'eq_ap_days',
        nameEn: 'DPO',
        nameZh: '应付账款周转天数',
        syntax: '365 * 平均应付账款 / 营业成本',
        descriptionEn: 'Days payables outstanding approximation.',
        descriptionZh: '采购付款周期近似。',
        insertTemplate: '365 * 平均应付账款 / 营业成本',
        caretHint: 'end',
        tags: ['DPO', '应付'],
      },
      {
        id: 'eq_ccc',
        nameEn: 'cash conversion cycle',
        nameZh: '现金转换周期',
        syntax: '存货天数 + 应收天数 - 应付天数',
        descriptionZh: '营运资金占用周期粗略指标。',
        descriptionEn: 'CCC ≈ DIO + DSO - DPO.',
        insertTemplate: '存货天数 + 应收天数 - 应付天数',
        caretHint: 'end',
        tags: ['CCC', '营运资本'],
      },
      {
        id: 'eq_div_payout',
        nameEn: 'payout ratio',
        nameZh: '股息支付率',
        syntax: '每股股息 / 每股收益',
        descriptionZh: '利润中用于分红的比例。',
        descriptionEn: 'DPS / EPS.',
        insertTemplate: '每股股息 / 每股收益',
        caretHint: 'end',
        tags: ['股息', '支付率'],
      },
      {
        id: 'eq_retention',
        nameEn: 'retention ratio',
        nameZh: '利润留存率',
        syntax: '1 - 股息支付率',
        descriptionZh: '或 (净利润-分红)/净利润。',
        descriptionEn: '1 - payout ratio.',
        insertTemplate: '1 - 股息支付率',
        caretHint: 'end',
        tags: ['留存率', '再投资'],
      },
      {
        id: 'eq_sustainable_g',
        nameEn: 'sustainable g',
        nameZh: '可持续增长率',
        syntax: 'ROE * 留存率',
        descriptionZh: '不增发下内部增长近似上界；杜邦 ROE 须与留存率口径一致。',
        descriptionEn: 'g ≈ ROE × retention (sustainable growth).',
        insertTemplate: 'ROE * 留存率',
        caretHint: 'end',
        tags: ['可持续增长', 'g'],
      },
      {
        id: 'eq_beta_portfolio',
        nameEn: 'portfolio beta',
        nameZh: '组合 β',
        syntax: 'w1*β1 + w2*β2 + …',
        descriptionZh: '权重为市值或目标权重；β 为相对市场的回归系数。',
        descriptionEn: 'Weighted sum of asset betas.',
        insertTemplate: 'w1 * β1 + w2 * β2',
        caretHint: 'end',
        tags: ['beta', '组合'],
      },
      {
        id: 'eq_treynor',
        nameEn: 'Treynor',
        nameZh: '特雷诺比率',
        syntax: '(Rp - Rf) / βp',
        descriptionZh: '单位系统风险超额收益；Rp、Rf 同期。',
        descriptionEn: '(Portfolio return - risk-free) / beta.',
        insertTemplate: '(组合收益率 - 无风险利率) / βp',
        caretHint: 'end',
        tags: ['Treynor', '风险调整'],
      },
      {
        id: 'eq_sortino_simple',
        nameEn: 'Sortino (simple)',
        nameZh: '索提诺（简）',
        syntax: '(Rp - MAR) / downside deviation',
        descriptionZh: '下行波动需用收益低于 MAR 的子样本算 std；此处仅作结构提示。',
        descriptionEn: 'Excess return over MAR divided by downside deviation (define subset).',
        insertTemplate: '(组合收益率 - MAR) / 下行波动',
        caretHint: 'end',
        tags: ['Sortino', '下行风险'],
      },
      {
        id: 'eq_wacc',
        nameEn: 'WACC',
        nameZh: '加权平均资本成本',
        syntax: 'E/V*Re + D/V*Rd*(1-Tc)',
        descriptionZh: 'E 股权市值，D 净债，V=E+D；Re、Rd 为股权/债务成本；Tc 所得税率。',
        descriptionEn: 'Weighted average cost of capital.',
        insertTemplate: 'E/V * Re + D/V * Rd * (1 - Tc)',
        caretHint: 'end',
        tags: ['WACC', '资本成本'],
      },
    ],
  },
  {
    id: 'math',
    labelKey: 'calculator.fnCategory.math',
    order: 2,
    functions: [
      { id: 'abs', nameEn: 'abs', nameZh: '绝对值', syntax: 'abs(x)', descriptionZh: '非负数；用于距离、误差等。', descriptionEn: 'Absolute value; distance, magnitude.', insertTemplate: 'abs()', caretHint: 'firstParenInside', tags: ['abs'] },
      { id: 'sign', nameEn: 'sign', nameZh: '符号', syntax: 'sign(x)', descriptionZh: '正为 1，负为 -1，零为 0。', descriptionEn: 'Sign: 1, -1, or 0.', insertTemplate: 'sign()', caretHint: 'firstParenInside', tags: ['sign', '符号'] },
      { id: 'sqrt', nameEn: 'sqrt', nameZh: '平方根', syntax: 'sqrt(x)', descriptionZh: 'x≥0 时为算术平方根。', descriptionEn: 'Square root for x ≥ 0.', insertTemplate: 'sqrt()', caretHint: 'firstParenInside', tags: ['sqrt', '根'] },
      { id: 'cbrt', nameEn: 'cbrt', nameZh: '立方根', syntax: 'cbrt(x)', descriptionZh: '任意实数的立方根。', descriptionEn: 'Cube root.', insertTemplate: 'cbrt()', caretHint: 'firstParenInside', tags: ['cbrt', '立方根'] },
      { id: 'pow', nameEn: 'pow', nameZh: '幂', syntax: 'pow(x, y)', descriptionZh: 'x 的 y 次幂；复利、增长常用。', descriptionEn: 'x to the power y; compound growth.', insertTemplate: 'pow(, )', caretHint: 'firstParenInside', tags: ['pow', '幂'] },
      { id: 'mod', nameEn: 'mod', nameZh: '取余', syntax: 'mod(x, y)', descriptionZh: 'x 除以 y 的余数（与除数同号约定以 math.js 为准）。', descriptionEn: 'Modulo remainder of x divided by y.', insertTemplate: 'mod(, )', caretHint: 'firstParenInside', tags: ['mod', '余数'] },
      { id: 'gcd', nameEn: 'gcd', nameZh: '最大公约数', syntax: 'gcd(a, b, ...)', descriptionZh: '整数或能化为整数时的最大公约数。', descriptionEn: 'Greatest common divisor.', insertTemplate: 'gcd(, )', caretHint: 'firstParenInside', tags: ['gcd', '公约数'] },
      { id: 'lcm', nameEn: 'lcm', nameZh: '最小公倍数', syntax: 'lcm(a, b, ...)', descriptionZh: '最小公倍数。', descriptionEn: 'Least common multiple.', insertTemplate: 'lcm(, )', caretHint: 'firstParenInside', tags: ['lcm', '公倍数'] },
      { id: 'factorial', nameEn: 'factorial', nameZh: '阶乘', syntax: 'factorial(n)', descriptionZh: 'n!；n 宜为非负整数。', descriptionEn: 'Factorial n!; n should be non-negative integer.', insertTemplate: 'factorial()', caretHint: 'firstParenInside', tags: ['factorial', '阶乘'] },
      { id: 'combinations', nameEn: 'combinations', nameZh: '组合 C', syntax: 'combinations(n, k)', descriptionZh: '从 n 个取 k 个的组合数 C(n,k)。', descriptionEn: 'Binomial coefficient C(n,k).', insertTemplate: 'combinations(, )', caretHint: 'firstParenInside', tags: ['combinations', '组合'] },
      { id: 'permutations', nameEn: 'permutations', nameZh: '排列 A', syntax: 'permutations(n, k)', descriptionZh: '从 n 个取 k 个的排列数。', descriptionEn: 'Permutations P(n,k).', insertTemplate: 'permutations(, )', caretHint: 'firstParenInside', tags: ['permutations', '排列'] },
      { id: 'round', nameEn: 'round', nameZh: '四舍五入', syntax: 'round(x, n?)', descriptionZh: '默认取整到整数；可指定小数位 n。', descriptionEn: 'Round to integer or n decimal places.', insertTemplate: 'round()', caretHint: 'firstParenInside', tags: ['round'] },
      { id: 'floor', nameEn: 'floor', nameZh: '向下取整', syntax: 'floor(x)', descriptionZh: '不大于 x 的最大整数。', descriptionEn: 'Greatest integer ≤ x.', insertTemplate: 'floor()', caretHint: 'firstParenInside', tags: ['floor'] },
      { id: 'ceil', nameEn: 'ceil', nameZh: '向上取整', syntax: 'ceil(x)', descriptionZh: '不小于 x 的最小整数。', descriptionEn: 'Smallest integer ≥ x.', insertTemplate: 'ceil()', caretHint: 'firstParenInside', tags: ['ceil'] },
      { id: 'min', nameEn: 'min', nameZh: '最小值', syntax: 'min(a, b, ...)', descriptionZh: '多参数或数组中的最小值。', descriptionEn: 'Minimum of arguments.', insertTemplate: 'min(, )', caretHint: 'firstParenInside', tags: ['min'] },
      { id: 'max', nameEn: 'max', nameZh: '最大值', syntax: 'max(a, b, ...)', descriptionZh: '多参数或数组中的最大值。', descriptionEn: 'Maximum of arguments.', insertTemplate: 'max(, )', caretHint: 'firstParenInside', tags: ['max'] },
      { id: 'sin', nameEn: 'sin', nameZh: '正弦', syntax: 'sin(x)', descriptionZh: '三角函数，x 为弧度。', descriptionEn: 'Sine; x in radians.', insertTemplate: 'sin()', caretHint: 'firstParenInside', tags: ['sin'] },
      { id: 'cos', nameEn: 'cos', nameZh: '余弦', syntax: 'cos(x)', descriptionZh: '三角函数，x 为弧度。', descriptionEn: 'Cosine; x in radians.', insertTemplate: 'cos()', caretHint: 'firstParenInside', tags: ['cos'] },
      { id: 'tan', nameEn: 'tan', nameZh: '正切', syntax: 'tan(x)', descriptionZh: '三角函数，x 为弧度。', descriptionEn: 'Tangent; x in radians.', insertTemplate: 'tan()', caretHint: 'firstParenInside', tags: ['tan'] },
      { id: 'log', nameEn: 'log', nameZh: '对数', syntax: 'log(x, base?)', descriptionZh: '默认自然对数为底时可配合 ln；指定 base 为以 base 为底。', descriptionEn: 'Logarithm; optional base.', insertTemplate: 'log()', caretHint: 'firstParenInside', tags: ['log'] },
      { id: 'ln', nameEn: 'ln', nameZh: '自然对数', syntax: 'ln(x)', descriptionZh: '以 e 为底，x>0。', descriptionEn: 'Natural log; x > 0.', insertTemplate: 'ln()', caretHint: 'firstParenInside', tags: ['ln'] },
      { id: 'exp', nameEn: 'exp', nameZh: 'e^x', syntax: 'exp(x)', descriptionZh: 'e 的 x 次幂。', descriptionEn: 'e raised to x.', insertTemplate: 'exp()', caretHint: 'firstParenInside', tags: ['exp'] },
      { id: 'asin', nameEn: 'asin', nameZh: '反正弦', syntax: 'asin(x)', descriptionZh: '反正弦，结果弧度，定义域 [-1,1]。', descriptionEn: 'Arcsine in radians; domain [-1, 1].', insertTemplate: 'asin()', caretHint: 'firstParenInside', tags: ['asin', '反三角'] },
      { id: 'acos', nameEn: 'acos', nameZh: '反余弦', syntax: 'acos(x)', descriptionZh: '反余弦，结果弧度。', descriptionEn: 'Arccosine in radians.', insertTemplate: 'acos()', caretHint: 'firstParenInside', tags: ['acos'] },
      { id: 'atan', nameEn: 'atan', nameZh: '反正切', syntax: 'atan(x)', descriptionZh: '反正切，结果弧度。', descriptionEn: 'Arctangent in radians.', insertTemplate: 'atan()', caretHint: 'firstParenInside', tags: ['atan'] },
      { id: 'atan2', nameEn: 'atan2', nameZh: '象限反正切', syntax: 'atan2(y, x)', descriptionZh: '根据 (x,y) 象限求角度（弧度），常用于向量方位。', descriptionEn: 'Two-argument arctangent; angle in radians.', insertTemplate: 'atan2(, )', caretHint: 'firstParenInside', tags: ['atan2', '方位'] },
      { id: 'hypot', nameEn: 'hypot', nameZh: '直角斜边', syntax: 'hypot(a, b, ...)', descriptionZh: 'sqrt(a²+b²+…)，求多维直角距离。', descriptionEn: 'Euclidean norm / hypotenuse.', insertTemplate: 'hypot(, )', caretHint: 'firstParenInside', tags: ['hypot', '距离'] },
      { id: 'log10', nameEn: 'log10', nameZh: '常用对数', syntax: 'log10(x)', descriptionZh: '以 10 为底，x>0。', descriptionEn: 'Base-10 logarithm; x > 0.', insertTemplate: 'log10()', caretHint: 'firstParenInside', tags: ['log10', 'lg'] },
      { id: 'nthRoot', nameEn: 'nthRoot', nameZh: 'n 次方根', syntax: 'nthRoot(a, n)', descriptionZh: 'a 的 n 次方根；如 nthRoot(27, 3)=3。', descriptionEn: 'n-th root of a.', insertTemplate: 'nthRoot(, )', caretHint: 'firstParenInside', tags: ['nthRoot', '开方'] },
      { id: 'sinh', nameEn: 'sinh', nameZh: '双曲正弦', syntax: 'sinh(x)', descriptionZh: '双曲正弦 sh x。', descriptionEn: 'Hyperbolic sine.', insertTemplate: 'sinh()', caretHint: 'firstParenInside', tags: ['sinh', '双曲'] },
      { id: 'cosh', nameEn: 'cosh', nameZh: '双曲余弦', syntax: 'cosh(x)', descriptionZh: '双曲余弦 ch x。', descriptionEn: 'Hyperbolic cosine.', insertTemplate: 'cosh()', caretHint: 'firstParenInside', tags: ['cosh', '双曲'] },
      { id: 'tanh', nameEn: 'tanh', nameZh: '双曲正切', syntax: 'tanh(x)', descriptionZh: '双曲正切 th x。', descriptionEn: 'Hyperbolic tangent.', insertTemplate: 'tanh()', caretHint: 'firstParenInside', tags: ['tanh', '双曲'] },
      { id: 'asinh', nameEn: 'asinh', nameZh: '反双曲正弦', syntax: 'asinh(x)', descriptionZh: 'area sinh，反双曲正弦。', descriptionEn: 'Inverse hyperbolic sine.', insertTemplate: 'asinh()', caretHint: 'firstParenInside', tags: ['asinh', '反双曲'] },
      { id: 'acosh', nameEn: 'acosh', nameZh: '反双曲余弦', syntax: 'acosh(x)', descriptionZh: '定义域 x≥1。', descriptionEn: 'Inverse hyperbolic cosine; x ≥ 1.', insertTemplate: 'acosh()', caretHint: 'firstParenInside', tags: ['acosh', '反双曲'] },
      { id: 'atanh', nameEn: 'atanh', nameZh: '反双曲正切', syntax: 'atanh(x)', descriptionZh: '定义域 |x|<1。', descriptionEn: 'Inverse hyperbolic tangent; |x| < 1.', insertTemplate: 'atanh()', caretHint: 'firstParenInside', tags: ['atanh', '反双曲'] },
      { id: 'csch', nameEn: 'csch', nameZh: '双曲余割', syntax: 'csch(x)', descriptionZh: '1/sinh(x)。', descriptionEn: 'Hyperbolic cosecant.', insertTemplate: 'csch()', caretHint: 'firstParenInside', tags: ['csch', '双曲'] },
      { id: 'sech', nameEn: 'sech', nameZh: '双曲正割', syntax: 'sech(x)', descriptionZh: '1/cosh(x)。', descriptionEn: 'Hyperbolic secant.', insertTemplate: 'sech()', caretHint: 'firstParenInside', tags: ['sech', '双曲'] },
      { id: 'coth', nameEn: 'coth', nameZh: '双曲余切', syntax: 'coth(x)', descriptionZh: 'cosh/sinh。', descriptionEn: 'Hyperbolic cotangent.', insertTemplate: 'coth()', caretHint: 'firstParenInside', tags: ['coth', '双曲'] },
      { id: 'csc', nameEn: 'csc', nameZh: '余割', syntax: 'csc(x)', descriptionZh: '1/sin(x)，x 为弧度。', descriptionEn: 'Cosecant; x in radians.', insertTemplate: 'csc()', caretHint: 'firstParenInside', tags: ['csc', '三角'] },
      { id: 'sec', nameEn: 'sec', nameZh: '正割', syntax: 'sec(x)', descriptionZh: '1/cos(x)。', descriptionEn: 'Secant.', insertTemplate: 'sec()', caretHint: 'firstParenInside', tags: ['sec', '三角'] },
      { id: 'cot', nameEn: 'cot', nameZh: '余切', syntax: 'cot(x)', descriptionZh: '1/tan(x)。', descriptionEn: 'Cotangent.', insertTemplate: 'cot()', caretHint: 'firstParenInside', tags: ['cot', '三角'] },
      { id: 'deg_rad', nameEn: 'deg → rad', nameZh: '角度转弧度', syntax: '角度 * pi / 180', descriptionZh: '三角函数使用弧度；度数为°时用此换算。', descriptionEn: 'Convert degrees to radians for trig.', insertTemplate: '角度 * pi / 180', caretHint: 'end', tags: ['弧度', '角度', 'deg'] },
      { id: 'erf', nameEn: 'erf', nameZh: '误差函数', syntax: 'erf(x)', descriptionZh: '高斯误差函数，统计与物理中常见。', descriptionEn: 'Error function.', insertTemplate: 'erf()', caretHint: 'firstParenInside', tags: ['erf', '正态'] },
      { id: 'gamma', nameEn: 'gamma', nameZh: 'Γ 函数', syntax: 'gamma(z)', descriptionZh: '阶乘推广 Γ(n)=(n-1)!（正整数时）。', descriptionEn: 'Gamma function.', insertTemplate: 'gamma()', caretHint: 'firstParenInside', tags: ['gamma', '阶乘'] },
      { id: 'lgamma', nameEn: 'lgamma', nameZh: 'log Γ', syntax: 'lgamma(z)', descriptionZh: 'ln Γ(z)，大数阶乘取对数时数值更稳。', descriptionEn: 'Log-gamma; stable for large z.', insertTemplate: 'lgamma()', caretHint: 'firstParenInside', tags: ['lgamma', '伽马'] },
    ],
  },
  {
    id: 'list',
    labelKey: 'calculator.fnCategory.list',
    order: 3,
    functions: [
      { id: 'list_len', nameEn: 'listLen', nameZh: '列表长度', syntax: 'listLen(data)', descriptionZh: '数值列表元素个数。', descriptionEn: 'Number of elements.', insertTemplate: 'listLen([])', caretHint: 'firstParenInside', tags: ['list', 'length'] },
      { id: 'list_at', nameEn: 'listAt', nameZh: '按索引取值', syntax: 'listAt(data, i)', descriptionZh: '1-based 索引；越界为 NaN。', descriptionEn: '1-based index; out of range → NaN.', insertTemplate: 'listAt([], 1)', caretHint: 'firstParenInside', tags: ['list', 'index'] },
      { id: 'list_slice', nameEn: 'listSlice', nameZh: '闭区间切片', syntax: 'listSlice(data, start, end)', descriptionZh: '1-based 闭区间 [start, end]。', descriptionEn: '1-based inclusive slice.', insertTemplate: 'listSlice([], 1, 3)', caretHint: 'firstParenInside', tags: ['list', 'slice'] },
      { id: 'list_concat', nameEn: 'listConcat', nameZh: '拼接列表', syntax: 'listConcat(a, b, ...)', descriptionZh: '多段数值列表顺序拼接；超长会截断。', descriptionEn: 'Concatenate lists; may clamp length.', insertTemplate: 'listConcat([], [])', caretHint: 'firstParenInside', tags: ['list', 'concat'] },
      { id: 'list_reverse', nameEn: 'listReverse', nameZh: '反转', syntax: 'listReverse(data)', descriptionZh: '新列表，元素顺序相反。', descriptionEn: 'Reversed copy.', insertTemplate: 'listReverse([])', caretHint: 'firstParenInside', tags: ['list', 'reverse'] },
      { id: 'list_diff', nameEn: 'listDiff', nameZh: '相邻差分', syntax: 'listDiff(data)', descriptionZh: '相邻项之差，长度 n-1。', descriptionEn: 'First differences.', insertTemplate: 'listDiff([])', caretHint: 'firstParenInside', tags: ['list', 'diff'] },
      { id: 'list_cumprod', nameEn: 'listCumprod', nameZh: '累乘', syntax: 'listCumprod(data)', descriptionZh: '前缀积。', descriptionEn: 'Cumulative product.', insertTemplate: 'listCumprod([])', caretHint: 'firstParenInside', tags: ['list', 'cumprod'] },
      { id: 'list_cumsum', nameEn: 'listCumsum', nameZh: '累加（别名）', syntax: 'listCumsum(data)', descriptionZh: '与 cumsum 等价；便于在列表分类中发现。', descriptionEn: 'Same as cumsum; list-namespace alias.', insertTemplate: 'listCumsum([])', caretHint: 'firstParenInside', tags: ['list', 'cumsum'] },
      { id: 'list_sort', nameEn: 'listSort', nameZh: '升序排序', syntax: 'listSort(data)', descriptionZh: '返回新数组，升序。', descriptionEn: 'Sorted ascending.', insertTemplate: 'listSort([])', caretHint: 'firstParenInside', tags: ['list', 'sort'] },
      { id: 'list_rank', nameEn: 'listRank', nameZh: '平均秩', syntax: 'listRank(data)', descriptionZh: '1-based 秩；并列取平均（类似 RANK.AVG）。', descriptionEn: '1-based ranks; ties averaged.', insertTemplate: 'listRank([])', caretHint: 'firstParenInside', tags: ['list', 'rank'] },
      { id: 'list_unique', nameEn: 'listUnique', nameZh: '去重保序', syntax: 'listUnique(data)', descriptionZh: '保留首次出现顺序。', descriptionEn: 'Unique preserving first occurrence order.', insertTemplate: 'listUnique([])', caretHint: 'firstParenInside', tags: ['list', 'unique'] },
      { id: 'list_indexof', nameEn: 'listIndexOf', nameZh: '查找位置', syntax: 'listIndexOf(value, keys)', descriptionZh: '精确匹配 keys 中首次出现，1-based；未找到 NaN。', descriptionEn: 'First match 1-based; else NaN.', insertTemplate: 'listIndexOf(1, [])', caretHint: 'firstParenInside', tags: ['list', 'indexOf'] },
      { id: 'list_lookup', nameEn: 'listLookup', nameZh: '键值查找', syntax: 'listLookup(value, keys, values)', descriptionZh: 'keys 与 values 等长；精确匹配首个 key。', descriptionEn: 'Parallel keys/values lookup.', insertTemplate: 'listLookup(1, [], [])', caretHint: 'firstParenInside', tags: ['list', 'lookup'] },
      { id: 'roll_mean', nameEn: 'rollMean', nameZh: '滚动平均', syntax: 'rollMean(data, window)', descriptionZh: '尾部窗口；前 window-1 项为 NaN。', descriptionEn: 'Trailing window mean; leading NaNs.', insertTemplate: 'rollMean([], 3)', caretHint: 'firstParenInside', tags: ['list', 'rolling', 'mean'] },
      { id: 'roll_sum', nameEn: 'rollSum', nameZh: '滚动求和', syntax: 'rollSum(data, window)', descriptionZh: '尾部窗口；前 window-1 项为 NaN。', descriptionEn: 'Trailing window sum; leading NaNs.', insertTemplate: 'rollSum([], 3)', caretHint: 'firstParenInside', tags: ['list', 'rolling', 'sum'] },
      { id: 'list_fill', nameEn: 'listFill', nameZh: '常量填充', syntax: 'listFill(n, value)', descriptionZh: '长度为 n 的常数列表。', descriptionEn: 'Constant vector of length n.', insertTemplate: 'listFill(5, 0)', caretHint: 'firstParenInside', tags: ['list', 'fill'] },
      { id: 'list_range', nameEn: 'listRange', nameZh: '整数范围', syntax: 'listRange(start, end, step?)', descriptionZh: '含端点步进序列；step 可负。', descriptionEn: 'Inclusive stepped range; step may be negative.', insertTemplate: 'listRange(1, 10)', caretHint: 'firstParenInside', tags: ['list', 'range'] },
      { id: 'list_quantile', nameEn: 'listQuantile', nameZh: '分位数', syntax: 'listQuantile(data, p)', descriptionZh: 'p∈[0,1]；基于 quantileSeq。', descriptionEn: 'Quantile; uses quantileSeq.', insertTemplate: 'listQuantile([], 0.5)', caretHint: 'firstParenInside', tags: ['list', 'quantile'] },
      { id: 'list_argsort', nameEn: 'listArgSort', nameZh: '排序索引', syntax: 'listArgSort(data)', descriptionZh: '升序排列对应的原始位置（1-based）。', descriptionEn: '1-based indices sorting order.', insertTemplate: 'listArgSort([])', caretHint: 'firstParenInside', tags: ['list', 'argsort', 'order'] },
      { id: 'list_mean', nameEn: 'listMean', nameZh: '列表均值', syntax: 'listMean(data)', descriptionZh: '计算列表中所有元素的算术平均值。', descriptionEn: 'Arithmetic mean of all elements.', insertTemplate: 'listMean([])', caretHint: 'firstParenInside', tags: ['list', 'mean', 'average'] },
    ],
  },

  {
    id: 'spreadsheet',
    labelKey: 'calculator.fnCategory.spreadsheet',
    order: 4,
    functions: [
      { id: 'xl_sum', nameEn: 'SUM', nameZh: '求和', syntax: 'SUM(a, b, ...)', descriptionZh: '与 sum 等价；大写便于自 Excel / WPS 迁移。', descriptionEn: 'Same as sum(); uppercase for spreadsheet habit.', insertTemplate: 'SUM()', caretHint: 'firstParenInside', tags: ['Excel', 'WPS', 'SUM'] },
      { id: 'xl_average', nameEn: 'AVERAGE', nameZh: '平均值', syntax: 'AVERAGE(...)', descriptionZh: '与 mean 等价。', descriptionEn: 'Same as mean.', insertTemplate: 'AVERAGE()', caretHint: 'firstParenInside', tags: ['AVERAGE', 'Excel'] },
      { id: 'xl_count', nameEn: 'COUNT', nameZh: '计数', syntax: 'COUNT(...)', descriptionZh: '统计数值个数（数组展开后计元素）。', descriptionEn: 'Count numeric values.', insertTemplate: 'COUNT()', caretHint: 'firstParenInside', tags: ['COUNT', 'Excel'] },
      { id: 'xl_stdev', nameEn: 'STDEV / STDEV.S', nameZh: '样本标准差', syntax: 'STDEV(...)', descriptionZh: '与 std 一致（无偏样本）。STDEVP 为总体标准差。', descriptionEn: 'Sample std; STDEVP is population.', insertTemplate: 'STDEV()', caretHint: 'firstParenInside', tags: ['STDEV', '标准差'] },
      { id: 'xl_var', nameEn: 'VAR / VAR.S', nameZh: '样本方差', syntax: 'VAR(...)', descriptionZh: 'VARP 为总体方差。', descriptionEn: 'Sample variance; VARP population.', insertTemplate: 'VAR()', caretHint: 'firstParenInside', tags: ['VAR', '方差'] },
      { id: 'xl_correl', nameEn: 'CORREL', nameZh: '相关系数', syntax: 'CORREL(A, B)', descriptionZh: '与 corr 等价，两列等长数据。', descriptionEn: 'Same as corr.', insertTemplate: 'CORREL([], [])', caretHint: 'firstParenInside', tags: ['CORREL', '相关'] },
      { id: 'xl_power', nameEn: 'POWER', nameZh: '幂', syntax: 'POWER(x, y)', descriptionZh: '与 pow(x,y) 等价。', descriptionEn: 'Same as pow.', insertTemplate: 'POWER(, )', caretHint: 'firstParenInside', tags: ['POWER', '幂'] },
      { id: 'xl_log', nameEn: 'LOG', nameZh: '对数', syntax: 'LOG(x) 或 LOG(x, base)', descriptionZh: '单参数为常用对数（底 10）；两参数为指定底。', descriptionEn: 'LOG(x)=log10(x); LOG(x,b)=log_b(x).', insertTemplate: 'LOG()', caretHint: 'firstParenInside', tags: ['LOG', '对数'] },
      { id: 'xl_ln', nameEn: 'LN', nameZh: '自然对数', syntax: 'LN(x)', descriptionZh: '与 ln(x) 等价。', descriptionEn: 'Natural log.', insertTemplate: 'LN()', caretHint: 'firstParenInside', tags: ['LN'] },
      { id: 'xl_pi', nameEn: 'PI', nameZh: '圆周率', syntax: 'PI()', descriptionZh: '返回 π，与常量 pi 一致。', descriptionEn: 'Returns π.', insertTemplate: 'PI()', caretHint: 'firstParenInside', tags: ['PI', 'π'] },
      { id: 'xl_degrees', nameEn: 'DEGREES', nameZh: '弧度→度', syntax: 'DEGREES(x)', descriptionZh: '弧度转角度。', descriptionEn: 'Radians to degrees.', insertTemplate: 'DEGREES()', caretHint: 'firstParenInside', tags: ['DEGREES', '角度'] },
      { id: 'xl_radians', nameEn: 'RADIANS', nameZh: '度→弧度', syntax: 'RADIANS(x)', descriptionZh: '角度转弧度。', descriptionEn: 'Degrees to radians.', insertTemplate: 'RADIANS()', caretHint: 'firstParenInside', tags: ['RADIANS', '弧度'] },
      { id: 'xl_round', nameEn: 'ROUND / ROUNDDOWN / ROUNDUP', nameZh: '舍入', syntax: 'ROUND(x, n?)', descriptionZh: 'ROUNDDOWN/ROUNDUP 与 floor/ceil 按小数位对齐 Excel 习惯（详见 math.js）。', descriptionEn: 'Rounding; see math.js for edge cases.', insertTemplate: 'ROUND(, 2)', caretHint: 'firstParenInside', tags: ['ROUND', '舍入'] },
      { id: 'xl_xnpv', nameEn: 'XNPV', nameZh: '不规则日期净现值', syntax: 'XNPV(rate, values, dates)', descriptionZh: '与 xnpv 相同；大写与 Excel 一致。', descriptionEn: 'Same as xnpv.', insertTemplate: 'XNPV(0.1, [], [])', caretHint: 'firstParenInside', tags: ['XNPV', 'Excel'] },
      { id: 'xl_xirr', nameEn: 'XIRR', nameZh: '不规则日期收益率', syntax: 'XIRR(values, dates, guess?)', descriptionZh: '与 xirr 相同。', descriptionEn: 'Same as xirr.', insertTemplate: 'XIRR([], [], 0.1)', caretHint: 'firstParenInside', tags: ['XIRR', 'Excel'] },
      { id: 'xl_norm_s_dist', nameEn: 'NORM_S_DIST', nameZh: '标准正态 PDF/CDF', syntax: 'NORM_S_DIST(z, cumulative)', descriptionZh: '与 normSdist 相同。', descriptionEn: 'Same as normSdist.', insertTemplate: 'NORM_S_DIST(0, 1)', caretHint: 'firstParenInside', tags: ['Excel', '正态'] },
      { id: 'xl_norm_s_inv', nameEn: 'NORM_S_INV', nameZh: '标准正态分位数', syntax: 'NORM_S_INV(p)', descriptionZh: '与 normsinv 相同。', descriptionEn: 'Same as normsinv.', insertTemplate: 'NORM_S_INV(0.5)', caretHint: 'firstParenInside', tags: ['Excel'] },
      { id: 'xl_norm_dist', nameEn: 'NORM_DIST', nameZh: '一般正态', syntax: 'NORM_DIST(x, mean, sd, cumulative)', descriptionZh: '与 normdist 相同。', descriptionEn: 'Same as normdist.', insertTemplate: 'NORM_DIST(0, 0, 1, 1)', caretHint: 'firstParenInside', tags: ['Excel'] },
      { id: 'xl_slope', nameEn: 'SLOPE', nameZh: '斜率', syntax: 'SLOPE(known_y, known_x)', descriptionZh: '与 slope 相同。', descriptionEn: 'Same as slope.', insertTemplate: 'SLOPE([], [])', caretHint: 'firstParenInside', tags: ['Excel'] },
      { id: 'xl_intercept', nameEn: 'INTERCEPT', nameZh: '截距', syntax: 'INTERCEPT(known_y, known_x)', descriptionZh: '与 intercept 相同。', descriptionEn: 'Same as intercept.', insertTemplate: 'INTERCEPT([], [])', caretHint: 'firstParenInside', tags: ['Excel'] },
      { id: 'xl_rsq', nameEn: 'RSQ', nameZh: 'r²', syntax: 'RSQ(known_y, known_x)', descriptionZh: '与 rsq 相同。', descriptionEn: 'Same as rsq.', insertTemplate: 'RSQ([], [])', caretHint: 'firstParenInside', tags: ['Excel'] },
      { id: 'xl_and', nameEn: 'AND / OR / NOT', nameZh: '逻辑', syntax: 'AND(a, b, ...)', descriptionZh: '多参数从左结合；用于条件组合（结果为布尔）。', descriptionEn: 'Chained boolean ops.', insertTemplate: 'AND(, )', caretHint: 'firstParenInside', tags: ['AND', '逻辑'] },
    ],
  },
  {
    id: 'statistics',
    labelKey: 'calculator.fnCategory.statistics',
    order: 5,
    functions: [
      { id: 'sum', nameEn: 'sum', nameZh: '求和', syntax: 'sum(a, b, ...)', descriptionZh: '多项或数组元素之和。', descriptionEn: 'Sum of values.', insertTemplate: 'sum()', caretHint: 'firstParenInside', tags: ['sum', '合计'] },
      { id: 'mean', nameEn: 'mean', nameZh: '平均值', syntax: 'mean(a, b, ...)', descriptionZh: '算术平均。', descriptionEn: 'Arithmetic mean.', insertTemplate: 'mean()', caretHint: 'firstParenInside', tags: ['mean', '平均'] },
      { id: 'median', nameEn: 'median', nameZh: '中位数', syntax: 'median(a, b, ...)', descriptionZh: '排序后居中的值（偶数个时取中间两数平均）。', descriptionEn: 'Median value.', insertTemplate: 'median()', caretHint: 'firstParenInside', tags: ['median'] },
      { id: 'mode', nameEn: 'mode', nameZh: '众数', syntax: 'mode(a, b, ...)', descriptionZh: '出现次数最多的值；可能返回多个（数组）。', descriptionEn: 'Mode(s); may return multiple values.', insertTemplate: 'mode()', caretHint: 'firstParenInside', tags: ['mode', '众数'] },
      { id: 'std', nameEn: 'std', nameZh: '标准差', syntax: 'std(a, b, ...)', descriptionZh: '样本标准差（math.js 默认口径）。', descriptionEn: 'Standard deviation (math.js default).', insertTemplate: 'std()', caretHint: 'firstParenInside', tags: ['std', '标准差'] },
      { id: 'variance', nameEn: 'variance', nameZh: '方差', syntax: 'variance(a, b, ...)', descriptionZh: '离散程度；与标准差平方一致（同口径下）。', descriptionEn: 'Variance.', insertTemplate: 'variance()', caretHint: 'firstParenInside', tags: ['variance', '方差'] },
      { id: 'mad', nameEn: 'mad', nameZh: '平均绝对离差', syntax: 'mad(a, b, ...)', descriptionZh: '各值与中位数绝对偏差的平均值，稳健离散指标。', descriptionEn: 'Median absolute deviation (robust spread).', insertTemplate: 'mad()', caretHint: 'firstParenInside', tags: ['mad', '离差'] },
      { id: 'prod', nameEn: 'prod', nameZh: '连乘', syntax: 'prod(a, b, ...)', descriptionZh: '数组或参数连乘。', descriptionEn: 'Product of values.', insertTemplate: 'prod()', caretHint: 'firstParenInside', tags: ['prod', '乘积'] },
      { id: 'quantileSeq', nameEn: 'quantileSeq', nameZh: '分位数', syntax: 'quantileSeq(data, prob)', descriptionZh: '有序数据的分位数，prob 为 0~1（如 0.25 下四分位）。', descriptionEn: 'Quantile of sorted data; prob in [0, 1].', insertTemplate: 'quantileSeq([], 0.5)', caretHint: 'firstParenInside', tags: ['quantile', '分位'] },
      { id: 'corr', nameEn: 'corr', nameZh: '皮尔逊相关', syntax: 'corr(A, B)', descriptionZh: '两等长数组的线性相关系数 ∈[-1,1]。', descriptionEn: 'Pearson correlation of two vectors.', insertTemplate: 'corr([], [])', caretHint: 'firstParenInside', tags: ['corr', '相关', '皮尔逊'] },
      { id: 'cumsum', nameEn: 'cumsum', nameZh: '累加和', syntax: 'cumsum(data)', descriptionZh: '返回前缀和数组，与序列分析、净值曲线类似。', descriptionEn: 'Cumulative sum vector.', insertTemplate: 'cumsum([])', caretHint: 'firstParenInside', tags: ['cumsum', '前缀和'] },
      { id: 'stat_cv', nameEn: 'CV', nameZh: '变异系数', syntax: 'std(data) / mean(data)', descriptionZh: '无量纲离散度，可比不同量纲序列；mean≈0 时勿用。', descriptionEn: 'Coefficient of variation σ/μ.', insertTemplate: 'std(data) / mean(data)', caretHint: 'end', tags: ['CV', '变异系数'] },
      { id: 'stat_z', nameEn: 'z-score', nameZh: '标准分数', syntax: '(x - mean(data)) / std(data)', descriptionZh: '单点相对样本均值的标准差倍数。', descriptionEn: 'Standard score vs sample.', insertTemplate: '(x - mean(data)) / std(data)', caretHint: 'end', tags: ['z-score', '标准化'] },
      { id: 'stat_iqr', nameEn: 'IQR', nameZh: '四分位距', syntax: 'Q3 - Q1', descriptionZh: 'Q3=quantileSeq(data,0.75)，Q1=quantileSeq(data,0.25)。', descriptionEn: 'Interquartile range.', insertTemplate: 'quantileSeq(data, 0.75) - quantileSeq(data, 0.25)', caretHint: 'end', tags: ['IQR', '箱线图'] },
      { id: 'stat_sse', nameEn: 'SSE', nameZh: '残差平方和', syntax: 'sum(dotMultiply(y - yhat, y - yhat))', descriptionZh: 'y、yhat 为等长数组；与逐元残差平方和等价。', descriptionEn: 'Element-wise squared errors then sum.', insertTemplate: 'sum(dotMultiply(y - yhat, y - yhat))', caretHint: 'end', tags: ['SSE', '回归'] },
      { id: 'normsdist', nameEn: 'normsdist', nameZh: '标准正态分布函数', syntax: 'normsdist(z)', descriptionZh: 'Φ(z)，标准正态累积分布。', descriptionEn: 'Standard normal CDF.', insertTemplate: 'normsdist(0)', caretHint: 'firstParenInside', tags: ['正态', 'NORM.S.DIST'] },
      { id: 'normsinv', nameEn: 'normsinv', nameZh: '标准正态分位数', syntax: 'normsinv(p)', descriptionZh: 'Φ⁻¹(p)，p∈(0,1)。', descriptionEn: 'Standard normal inverse CDF.', insertTemplate: 'normsinv(0.5)', caretHint: 'firstParenInside', tags: ['正态', 'NORM.S.INV'] },
      { id: 'normdist', nameEn: 'normdist', nameZh: '一般正态分布', syntax: 'normdist(x, mean, sd, cumulative)', descriptionZh: 'cumulative 为 0 时返回密度，非 0 时返回累积概率。', descriptionEn: 'Normal PDF or CDF.', insertTemplate: 'normdist(0, 0, 1, 1)', caretHint: 'firstParenInside', tags: ['NORM.DIST'] },
      { id: 'normSdist2', nameEn: 'normSdist', nameZh: '标准正态 PDF/CDF', syntax: 'normSdist(z, cumulative)', descriptionZh: '第二参数为 0 返回 PDF，否则 CDF。', descriptionEn: 'NORM.S.DIST style.', insertTemplate: 'normSdist(0, 1)', caretHint: 'firstParenInside', tags: ['NORM.S.DIST'] },
      { id: 'slope_fn', nameEn: 'slope', nameZh: '斜率', syntax: 'slope(known_y, known_x)', descriptionZh: '与 Excel SLOPE 一致：第一参数为 y，第二为 x。', descriptionEn: 'Linear regression slope.', insertTemplate: 'slope([], [])', caretHint: 'firstParenInside', tags: ['SLOPE', '回归'] },
      { id: 'intercept_fn', nameEn: 'intercept', nameZh: '截距', syntax: 'intercept(known_y, known_x)', descriptionZh: '线性回归截距。', descriptionEn: 'Regression intercept.', insertTemplate: 'intercept([], [])', caretHint: 'firstParenInside', tags: ['INTERCEPT'] },
      { id: 'rsq_fn', nameEn: 'rsq', nameZh: '判定系数 r²', syntax: 'rsq(known_y, known_x)', descriptionZh: 'Pearson 相关系数平方，对齐 Excel RSQ。', descriptionEn: 'R-squared.', insertTemplate: 'rsq([], [])', caretHint: 'firstParenInside', tags: ['RSQ', 'r2'] },
      { id: 'stat_percentile', nameEn: 'percentile', nameZh: '百分位数', syntax: 'percentile(data, p)', descriptionZh: '计算第 p 百分位数（p 为 0-100）。', descriptionEn: 'p-th percentile (0-100).', insertTemplate: 'percentile([], )', caretHint: 'firstParenInside', tags: ['percentile', '百分位'] },
      { id: 'stat_geomean', nameEn: 'geomean', nameZh: '几何平均', syntax: 'geomean(data)', descriptionZh: '几何平均值；所有值必须为正数。', descriptionEn: 'Geometric mean; all values must be positive.', insertTemplate: 'geomean()', caretHint: 'firstParenInside', tags: ['geomean', '几何平均'] },
      { id: 'stat_harmean', nameEn: 'harmean', nameZh: '调和平均', syntax: 'harmean(data)', descriptionZh: '调和平均值。', descriptionEn: 'Harmonic mean.', insertTemplate: 'harmean()', caretHint: 'firstParenInside', tags: ['harmean', '调和平均'] },
      { id: 'stat_skew', nameEn: 'skew', nameZh: '偏度', syntax: 'skew(data)', descriptionZh: '样本偏度（三阶中心矩）。', descriptionEn: 'Sample skewness.', insertTemplate: 'skew()', caretHint: 'firstParenInside', tags: ['skew', '偏度'] },
      { id: 'stat_kurt', nameEn: 'kurt', nameZh: '峰度', syntax: 'kurt(data)', descriptionZh: '样本超额峰度。', descriptionEn: 'Sample excess kurtosis.', insertTemplate: 'kurt()', caretHint: 'firstParenInside', tags: ['kurt', '峰度'] },
    ],
  },
  {
    id: 'life',
    labelKey: 'calculator.fnCategory.life',
    order: 6,
    functions: [
      {
        id: 'life_bmi',
        nameEn: 'BMI',
        nameZh: '体质指数',
        syntax: '体重kg / (身高m)²',
        descriptionZh: '体重(kg)÷身高(米)²；身高常用厘米时可写 体重 / (身高cm/100)²。',
        descriptionEn: 'kg / m²; or kg / (cm/100)².',
        insertTemplate: '体重kg / (身高m) ^ 2',
        caretHint: 'end',
        tags: ['BMI', '健康', '体重'],
      },
      {
        id: 'life_bmi_cm',
        nameEn: 'BMI (cm)',
        nameZh: 'BMI（身高厘米）',
        syntax: '体重 / (身高cm/100)²',
        descriptionZh: '与上一项等价，直接代入厘米身高。',
        descriptionEn: 'Same as BMI with height in cm.',
        insertTemplate: '体重kg / (身高cm / 100) ^ 2',
        caretHint: 'end',
        tags: ['BMI', '厘米'],
      },
      {
        id: 'life_tip',
        nameEn: 'tip',
        nameZh: '小费（比例）',
        syntax: '账单 * 比例',
        descriptionZh: '比例用小数（如 0.15 表示 15%）。',
        descriptionEn: 'Bill times tip rate (0.15 = 15%).',
        insertTemplate: '账单 * 0.15',
        caretHint: 'end',
        tags: ['小费', 'tip', '餐饮'],
      },
      {
        id: 'life_split_bill',
        nameEn: 'split bill',
        nameZh: '人均分摊',
        syntax: '总金额 / 人数',
        descriptionZh: '聚餐、合租费用均摊。',
        descriptionEn: 'Equal split per person.',
        insertTemplate: '总金额 / 人数',
        caretHint: 'end',
        tags: ['AA', '分摊', '人均'],
      },
      {
        id: 'life_discount',
        nameEn: 'discount',
        nameZh: '折后价',
        syntax: '标价 * (1 - 折扣率)',
        descriptionZh: '折扣率为小数（如 0.2 表示减价 20% / 打八折）。',
        descriptionEn: 'Price after percent-off.',
        insertTemplate: '标价 * (1 - 0.2)',
        caretHint: 'end',
        tags: ['折扣', '促销'],
      },
      {
        id: 'life_tax_inclusive',
        nameEn: 'tax incl.',
        nameZh: '含税价反推不含税',
        syntax: '含税价 / (1 + 税率)',
        descriptionZh: '增值税价税分离；税率为小数。',
        descriptionEn: 'Back out net from gross VAT.',
        insertTemplate: '含税价 / (1 + 税率)',
        caretHint: 'end',
        tags: ['税', '增值税', '价税'],
      },
      {
        id: 'life_fuel_l',
        nameEn: 'fuel (L/100km)',
        nameZh: '油耗升数',
        syntax: 'L/100km * 里程km / 100',
        descriptionZh: '已知百公里油耗与行驶公里数，求总耗油量（升）。',
        descriptionEn: 'Liters from L/100km and distance.',
        insertTemplate: '百公里升数 * 里程km / 100',
        caretHint: 'end',
        tags: ['油耗', '汽车', '升'],
      },
      {
        id: 'life_mpg_l100',
        nameEn: 'MPG ↔ L/100km',
        nameZh: '英里加仑与升百公里',
        syntax: '235.214 / MPG ≈ L/100km',
        descriptionZh: '美制 MPG 与 L/100km 近似换算（常数因英制加仑定义略有误差）。',
        descriptionEn: 'Approx. US MPG to L/100km.',
        insertTemplate: '235.214 / MPG',
        caretHint: 'end',
        tags: ['MPG', '油耗', '换算'],
      },
      {
        id: 'life_pace',
        nameEn: 'pace',
        nameZh: '配速（分/公里）',
        syntax: '(分*60+秒) / 距离km',
        descriptionZh: '跑步用时换算为每公里分钟数。',
        descriptionEn: 'Min/km from time and distance.',
        insertTemplate: '(分钟 * 60 + 秒) / 距离km / 60',
        caretHint: 'end',
        tags: ['跑步', '配速', '马拉松'],
      },
      {
        id: 'life_temp_c_f',
        nameEn: '°C → °F',
        nameZh: '摄氏转华氏',
        syntax: 'C * 9/5 + 32',
        descriptionZh: '气温换算。',
        descriptionEn: 'Celsius to Fahrenheit.',
        insertTemplate: '摄氏 * 9/5 + 32',
        caretHint: 'end',
        tags: ['温度', '华氏', '摄氏'],
      },
      {
        id: 'life_temp_f_c',
        nameEn: '°F → °C',
        nameZh: '华氏转摄氏',
        syntax: '(F - 32) * 5/9',
        descriptionEn: 'Fahrenheit to Celsius.',
        descriptionZh: '气温换算。',
        insertTemplate: '(华氏 - 32) * 5/9',
        caretHint: 'end',
        tags: ['温度', '换算'],
      },
      {
        id: 'life_work_hours',
        nameEn: 'work days hours',
        nameZh: '工时（天×时）',
        syntax: '天数 * 每日小时',
        descriptionZh: '粗略计工作量或加班费基数（不含法定规则）。',
        descriptionEn: 'Days times hours per day.',
        insertTemplate: '天数 * 每日小时',
        caretHint: 'end',
        tags: ['工时', '加班'],
      },
      {
        id: 'life_mortgage_afford',
        nameEn: 'payment share',
        nameZh: '月供占收入比',
        syntax: '月供 / 月收入',
        descriptionZh: '偿债占收入比例（小数）；与银行口径仅作参考。',
        descriptionEn: 'Payment to income ratio.',
        insertTemplate: '月供 / 月收入',
        caretHint: 'end',
        tags: ['房贷', '月供', '偿债'],
      },
      {
        id: 'life_unit_price',
        nameEn: 'unit price',
        nameZh: '单价比较',
        syntax: '总价 / 数量',
        descriptionZh: '大包装是否更便宜：比较每克/每毫升单价。',
        descriptionEn: 'Price per unit for comparison.',
        insertTemplate: '总价 / 数量',
        caretHint: 'end',
        tags: ['超市', '单价', '性价比'],
      },
    ],
  },
  {
    id: 'visualization',
    labelKey: 'calculator.fnCategory.visualization',
    order: 7,
    functions: [
      {
        id: 'chart_line',
        nameEn: 'chart(line)',
        nameZh: '折线图',
        syntax: 'chart(line, 标签, 数据, {title})',
        descriptionZh: '生成折线图；标签和数据可为变量名（数组）或内联数组',
        descriptionEn: 'Create a line chart; labels and data can be variable names (arrays) or inline arrays.',
        insertTemplate: 'chart(line, , , {title: ""})',
        caretHint: 'firstParenInside',
        tags: ['chart', '折线图', '可视化', '图表', 'line'],
      },
      {
        id: 'chart_bar',
        nameEn: 'chart(bar)',
        nameZh: '柱状图',
        syntax: 'chart(bar, 标签, 数据, {title})',
        descriptionZh: '生成柱状图',
        descriptionEn: 'Create a bar chart.',
        insertTemplate: 'chart(bar, , , {title: ""})',
        caretHint: 'firstParenInside',
        tags: ['chart', '柱状图', '可视化', 'bar'],
      },
      {
        id: 'chart_pie',
        nameEn: 'chart(pie)',
        nameZh: '饼图',
        syntax: 'chart(pie, 标签, 数据, {title})',
        descriptionZh: '生成饼图',
        descriptionEn: 'Create a pie chart.',
        insertTemplate: 'chart(pie, , , {title: ""})',
        caretHint: 'firstParenInside',
        tags: ['chart', '饼图', '可视化', 'pie'],
      },
      {
        id: 'chart_scatter',
        nameEn: 'chart(scatter)',
        nameZh: '散点图',
        syntax: 'chart(scatter, 标签, 数据, {title})',
        descriptionZh: '生成散点图',
        descriptionEn: 'Create a scatter chart.',
        insertTemplate: 'chart(scatter, , , {title: ""})',
        caretHint: 'firstParenInside',
        tags: ['chart', '散点图', '可视化', 'scatter'],
      },
      {
        id: 'chart_area',
        nameEn: 'chart(area)',
        nameZh: '面积图',
        syntax: 'chart(area, 标签, 数据, {title})',
        descriptionZh: '生成面积图',
        descriptionEn: 'Create an area chart.',
        insertTemplate: 'chart(area, , , {title: ""})',
        caretHint: 'firstParenInside',
        tags: ['chart', '面积图', '可视化', 'area'],
      },
      {
        id: 'sens',
        nameEn: 'sens()',
        nameZh: '敏感性分析',
        syntax: 'sens(表达式, 变量, [起始, 步长, 结束])',
        descriptionZh: '对指定变量进行敏感性分析，生成值-结果对照表',
        descriptionEn: 'Sensitivity analysis: vary a variable over a range and show result pairs.',
        insertTemplate: 'sens(, , [, , ])',
        caretHint: 'firstParenInside',
        tags: ['sens', '敏感性分析', 'what-if', '数据表', 'scenario'],
      },
      {
        id: 'fn_def',
        nameEn: 'fn',
        nameZh: '自定义函数',
        syntax: 'fn 函数名(参数) = 表达式',
        descriptionZh: '定义可复用的自定义函数；定义后可在后续行直接调用',
        descriptionEn: 'Define a reusable custom function callable in subsequent lines.',
        insertTemplate: 'fn (, ) = ',
        caretHint: 'firstParenInside',
        tags: ['fn', '自定义函数', 'function', '定义'],
      },
    ],
  },
  {
    id: 'engineering',
    labelKey: 'calculator.fnCategory.engineering',
    order: 8,
    functions: [
      {
        id: 'fn_hex',
        nameEn: 'hex(n)',
        nameZh: '十六进制',
        syntax: 'hex(255)',
        descriptionZh: '将十进制数转为十六进制字符串',
        descriptionEn: 'Convert decimal to hexadecimal string.',
        insertTemplate: 'hex(',
        caretHint: 'end',
        tags: ['hex', '十六进制', '进制'],
      },
      {
        id: 'fn_oct',
        nameEn: 'oct(n)',
        nameZh: '八进制',
        syntax: 'oct(255)',
        descriptionZh: '将十进制数转为八进制字符串',
        descriptionEn: 'Convert decimal to octal string.',
        insertTemplate: 'oct(',
        caretHint: 'end',
        tags: ['oct', '八进制', '进制'],
      },
      {
        id: 'fn_bin',
        nameEn: 'bin(n)',
        nameZh: '二进制',
        syntax: 'bin(255)',
        descriptionZh: '将十进制数转为二进制字符串',
        descriptionEn: 'Convert decimal to binary string.',
        insertTemplate: 'bin(',
        caretHint: 'end',
        tags: ['bin', '二进制', '进制'],
      },
      {
        id: 'fn_bitAnd',
        nameEn: 'bitAnd(a, b)',
        nameZh: '按位与',
        syntax: 'bitAnd(a, b)',
        descriptionZh: '按位 AND 运算',
        descriptionEn: 'Bitwise AND.',
        insertTemplate: 'bitAnd(, )',
        caretHint: 'firstParenInside',
        tags: ['bit', '按位', '位运算'],
      },
      {
        id: 'fn_bitOr',
        nameEn: 'bitOr(a, b)',
        nameZh: '按位或',
        syntax: 'bitOr(a, b)',
        descriptionZh: '按位 OR 运算',
        descriptionEn: 'Bitwise OR.',
        insertTemplate: 'bitOr(, )',
        caretHint: 'firstParenInside',
        tags: ['bit', '按位', '位运算'],
      },
      {
        id: 'fn_toRad',
        nameEn: 'toRad(deg)',
        nameZh: '角度转弧度',
        syntax: 'toRad(180)',
        descriptionZh: '将角度转为弧度',
        descriptionEn: 'Convert degrees to radians.',
        insertTemplate: 'toRad(',
        caretHint: 'end',
        tags: ['rad', 'deg', '弧度', '角度'],
      },
      {
        id: 'fn_toDeg',
        nameEn: 'toDeg(rad)',
        nameZh: '弧度转角度',
        syntax: 'toDeg(pi)',
        descriptionZh: '将弧度转为角度',
        descriptionEn: 'Convert radians to degrees.',
        insertTemplate: 'toDeg(',
        caretHint: 'end',
        tags: ['deg', 'rad', '角度', '弧度'],
      },
    ],
  },
  {
    id: 'syntax',
    labelKey: 'calculator.fnCategory.syntax',
    order: 9,
    functions: [
      {
        id: 'line_ref',
        nameEn: 'line n',
        nameZh: '第 n 行',
        syntax: 'line 1 或 第2行',
        descriptionZh: '引用其他行的计算结果',
        descriptionEn: 'Reference another line result.',
        insertTemplate: 'line 1',
        caretHint: 'end',
        tags: ['line', '行', '引用'],
      },
      {
        id: 'line_prev',
        nameEn: 'above / prev',
        nameZh: '上一行',
        syntax: '上一行 或 above 或 prev',
        descriptionZh: '引用紧邻上一行（上一答案）的数值结果，等价于 line N-1。',
        descriptionEn: "Reference the previous line's numeric result (same as line N-1).",
        insertTemplate: 'above',
        caretHint: 'end',
        tags: ['above', 'prev', '上一行', 'soulver'],
      },
      {
        id: 'soulver_subtotal',
        nameEn: 'subtotal line',
        nameZh: '小计行',
        syntax: '小计 或 subtotal（整行）',
        descriptionZh: '在「# 行为」为 Soulver 时，整行仅写小计/subtotal 可对上一标题或上一小计之后的普通数值行求和。',
        descriptionEn: 'With Soulver-style # headings, a lone 小计/subtotal line sums numeric rows since the last heading/subtotal.',
        insertTemplate: 'subtotal',
        caretHint: 'end',
        tags: ['小计', 'subtotal', '分段', 'soulver'],
      },
      {
        id: 'soulver_heading',
        nameEn: '# heading',
        nameZh: '标题行',
        syntax: '# 章节名',
        descriptionZh: '在设置中将「#」设为 Soulver 标题后，# 开头行作为分段起点，供小计聚合使用。',
        descriptionEn: 'When # lines are headings, they start a section for subtotals.',
        insertTemplate: '# ',
        caretHint: 'end',
        tags: ['#', '标题', 'heading', 'soulver'],
      },
      {
        id: 'all_lines',
        nameEn: 'all lines',
        nameZh: '所有行',
        syntax: 'sum(所有行) 或 sum(all lines)',
        descriptionZh: '当前行上方已成功求值的数值行组成的数组，供 sum、mean、max、min 等使用；勿单独赋值给变量。',
        descriptionEn: 'Array of numeric results from lines above the current line; use inside sum/mean/max/min; not for bare assignment.',
        insertTemplate: '所有行',
        caretHint: 'end',
        tags: ['所有行', 'all lines', '统计', 'sum'],
      },
      {
        id: 'assign',
        nameEn: 'variable =',
        nameZh: '变量赋值',
        syntax: '名称 = 表达式',
        descriptionZh: '定义变量供下行使用；支持中文变量名',
        descriptionEn: 'Assign variable for later lines; Chinese names supported.',
        insertTemplate: 'x = ',
        caretHint: 'end',
        tags: ['变量', '赋值', 'let'],
      },
      {
        id: 'quoted_display',
        nameEn: 'quoted display',
        nameZh: '双引号展示',
        syntax: '10 "万"、100 "元"',
        descriptionZh: '双引号内文字仅追加在结果栏，不参与运算；数量简写（1.5万、25k）仍用无引号写法才会参与乘法。',
        descriptionEn: 'Text in double quotes is appended to the result display only; unquoted 万/k/m still apply as multipliers.',
        insertTemplate: ' "元"',
        caretHint: 'end',
        tags: ['双引号', '单位', '展示', 'quote', 'suffix'],
      },
      {
        id: 'percent',
        nameEn: 'percent',
        nameZh: '百分比',
        syntax: '50%、打8折',
        descriptionZh: '百分数与折扣写法',
        descriptionEn: 'Percent and discount phrasing.',
        insertTemplate: '50%',
        caretHint: 'end',
        tags: ['%', '百分比', '折'],
      },
      {
        id: 'unit_cn',
        nameEn: '10k / 万',
        nameZh: '数量简写',
        syntax: '25k、1.5万',
        descriptionZh: '英文 k/m/b 与中文万/亿（乘法）；仅想在结果栏显示「万」「元」等请用双引号，如 100 "万元"。',
        descriptionEn: 'k/m/b and 万/亿 as multipliers; use quotes for display-only units, e.g. 100 "万".',
        insertTemplate: '1.5万',
        caretHint: 'end',
        tags: ['万', 'k', '单位'],
      },
      {
        id: 'const_pi',
        nameEn: 'pi',
        nameZh: '圆周率',
        syntax: 'pi',
        descriptionZh: 'math.js 常量 π，用于三角与弧度换算等。',
        descriptionEn: 'Constant π.',
        insertTemplate: 'pi',
        caretHint: 'end',
        tags: ['pi', 'π', '圆周率'],
      },
      {
        id: 'const_e',
        nameEn: 'e',
        nameZh: '自然常数',
        syntax: 'e',
        descriptionZh: 'math.js 常量 e，常用于 exp、连续复利等。',
        descriptionEn: "Euler's number e.",
        insertTemplate: 'e',
        caretHint: 'end',
        tags: ['e', '自然常数'],
      },
      {
        id: 'cross_sheet_ref',
        nameEn: 'Cross-sheet ref',
        nameZh: '跨表引用',
        syntax: 'Sheet1!变量名 / [年度预算]!总计 / Sheet1!$3',
        descriptionZh: '引用其他 Sheet 中定义的变量或行结果；Sheet 名含空格时用方括号。',
        descriptionEn: 'Reference a variable or line result from another sheet; use brackets for names with spaces.',
        insertTemplate: 'Sheet1!',
        caretHint: 'end',
        tags: ['!', '跨表', '引用', 'cross-sheet', 'sheet'],
      },
    ],
  },
];

/** 扁平列表（搜索用） */
export function getAllCalculatorFunctions(): CalculatorFunctionEntry[] {
  return CALCULATOR_FUNCTION_CATEGORIES.flatMap((c) => c.functions);
}

export function searchCalculatorFunctions(query: string): CalculatorFunctionEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return getAllCalculatorFunctions();
  return getAllCalculatorFunctions().filter((f) => {
    if (f.nameEn.toLowerCase().includes(q) || f.nameZh.includes(query)) return true;
    if (f.syntax.toLowerCase().includes(q)) return true;
    if (f.tags.some((t) => t.toLowerCase().includes(q))) return true;
    return false;
  });
}

/** 供 AI system 注入的短摘要（中英混排由模型理解） */
export function buildCalculatorSyntaxSummaryForAI(maxLen = 2800): string {
  const lines: string[] = [
    '【计算器可用能力摘要】',
    '- 变量：行首 `名称 = 表达式` 或 `let 名称 = 表达式`；支持中文变量名。',
    '- 标点与运算符（类 Soulver / 文本计算器）：可用 `*` `/` 或 `×` `÷`；数字间中点 `·` 可作乘号；`≤` `≥` `≠`；西式千分位逗号（如 1,234.56）会去掉后再算；顿号 `、` 可作列表逗号；自然语言 `乘以` `除以`（与变量/数字组合）；`‰` `‱`；全角/混用标点经 NFKC 与引擎规范化。',
    '- 设置：可将导出（TXT / CSV / Markdown）中表达式列显示为中文 `×` `÷`（与编辑区输入无关）。',
    '- 行引用：`line 1`、`第2行`；上一答案：`上一行`、`above`、`prev`（等价于 line N-1）；区间求和：`合计(第1到5行)` 等（见引擎预处理）。',
    '- Soulver 分段：设置中可将 `#` 设为标题；单独一行 `小计`/`subtotal` 对上一标题或上一小计之后的普通数值行求和；导入 .slvr 时默认启用标题模式。',
    '- 特殊：`所有行` / `all lines` 展开为当前行之前已有数值结果的数组，用于 `sum`/`mean`/`max`/`min` 等（不含注释/空行/错误行）。',
    '- 【列表】一维数值列表；listAt、listSlice、listConcat、listRank、rollMean、listRange 等；索引与切片均为 1-based，listSlice 为闭区间 [start, end]。可与 sum(所有行)、cumsum、listCumsum 等组合；超长列表在引擎内截断。',
    '- 双引号：`10 "万"` 结果栏在数值后追加展示；无引号的 `1.5万`、`25k` 仍为乘法简写。',
    '- 金融：npv、irr、xnpv、xirr、pmt、fv、pv、nper、rate、ipmt、ppmt、mirr 已注册；xnpv/xirr 需现金流与日期等长（日期规则见函数目录）；npv 支持 `(现金流, 折现率)` 或 `(折现率, 现金流)`；现金流用方括号；type 0=期末 1=期初。',
    '- 数学/统计：三角与反三角、双曲与反双曲（sinh/cosh/tanh、asinh/acosh/atanh、csch/sech/coth）、余割/正割/余切；erf、gamma、lgamma；asin/acos/atan/atan2、hypot、log10、nthRoot；统计含 corr、cumsum、mode、mad、prod、quantileSeq、CV/z-score/IQR/SSE；正态：normsdist、normsinv、normdist、normSdist；回归：slope、intercept、rsq（与 Excel 参数顺序一致，y 在 x 前）；另有 abs、sign、sqrt、cbrt、pow、mod、gcd、lcm、factorial、combinations、permutations、round、floor、ceil、min、max、sin、cos、tan、log、ln、exp、sum、mean、median、std、variance；常量 pi、e。',
    '- 股市与估值：PE/PB/PS、EV 系列、ROIC、周转与现金周期、股息与可持续增长、WACC、β 组合、Treynor/Sortino（简）等见目录「股市与估值」；均为四则与幂组合，口径（TTM/年报）须自行统一。',
    '- 生活：BMI、小费与分摊、折扣与价税分离、油耗与 MPG 换算、配速、温标、工时与月供收入比、单价比较等见目录「生活」；变量名请替换为实际数值或已定义变量。',
    '- Excel/WPS 风格：已注册 SUM、AVERAGE、COUNT、MEDIAN、PRODUCT、MIN、MAX、STDEV/STDEVS、STDEVP、VAR/VARS、VARP、CORREL、POWER、MOD、ROUND、ROUNDDOWN、ROUNDUP、FLOOR、CEILING、ABS、SQRT、LN、LOG（单参=常用对数）、LOG10、EXP、PI()、DEGREES、RADIANS、AND、OR、NOT、XNPV、XIRR、NORM_S_DIST、NORM_S_INV、NORM_DIST、SLOPE、INTERCEPT、RSQ 等大写别名；与 Excel 在舍入边界、负向 FLOOR 等细节上以 math.js 为准。',
    '- 【易错】pmt：贷款本金 pv 常写负数；nper(rate, -月供, 剩余本金) 中还款额符号需与 pmt 输出一致；xnpv/xirr 的 dates 须与现金流同序同长；勿编造 VLOOKUP、HLOOKUP、NETWORKDAYS 等未实现函数名。',
    '- 输出建议：若给出可复制单行表达式，请用 ```formula 代码块包裹，仅一行或一段可执行内容。',
    '',
    '【函数列表（名称 — 语法）】',
  ];
  for (const cat of [...CALCULATOR_FUNCTION_CATEGORIES].sort((a, b) => a.order - b.order)) {
    for (const f of cat.functions) {
      lines.push(`- ${f.nameEn} / ${f.nameZh}: ${f.syntax}`);
    }
  }
  let s = lines.join('\n');
  if (s.length > maxLen) {
    s = `${s.slice(0, maxLen)}\n…(truncated)`;
  }
  return s;
}
